language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Storez.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Storez-ios"
  - OSX_FRAMEWORK_SCHEME="Storez-osx"
  - TVOS_FRAMEWORK_SCHEME="Storez-tvos"
  - WATCHOS_FRAMEWORK_SCHEME="Storez-watchos"
  - IOS_SDK=iphonesimulator10.0
  - OSX_SDK=macosx10.11
  - TVOS_SDK=appletvsimulator9.0
  - WATCHOS_SDK=watchsimulator2.0
  matrix:
  - DESTINATION="OS=10.0,name=iPhone 6S"         SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"
  - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="NO"
before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- if [ $RUN_TESTS == "YES" ]; then xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME"
  -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO
  test | xcpretty -c; else xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk
  "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build
  | xcpretty -c; fi
notifications:
  email: false
  slack:
    secure: Bsp/d2Yq4U0YTaixIxtLqb8pu5FwcKAQ5QwAUo3MENrAP+8budG+ELqn6QIl32xrQxN3cjrzBkkhB/hBK3qcnaxdE/Yfs18zkjeBQG/BdhEE8y97i2VfHVJ2GjuG49wzwtW/6/dND261J0voaky6FU+O6kCbUXvsvAqGCUdBCZ4nuSyoAYmg7zoyvkd51OXtr3NUnAS3AGYTfAHDl5PH/6fYq8xrz721U7Ml53HC5QjuBVWGKPDtvhjwvGRX8g6CE+Yptr0YKUntaMsahZQs+H6HG3ylSMQV9EnhqRcRcaIebRzYypcb9KY/whwfJMzAvl7+lI/vWTD36aMAUDYFN08vDLRNaI1F9qsQlCc8ElPqFs6CaHaaDijtBQ8iVxE57/mcaNuQBHvfhrp+IBpRep4rYxV0EAZrMIRnXdUOhYwrS/xla+j+K2WkXQPjc9Ui8UyBSo1biUdE2bXFUT7g/J2AvW1rA6CqosjU9uT8K08jo3t1ixcreV1o5aKBKIPPQG/SeegefAaegqZyJHTA1Eac8eo9RlwOypI8cmWYa4QMKwArve7kor1/u6HNHD+832+LQ9qSQH7FAUAicEV5kXTA5k2m9vOrVKLIKcWFuo9ea1P52ecubmA4+Kmf/kpqbkE9Yntj9fWEHy54vAm+bPiMp7cb07sIeLoRY28PoM8=
